[package]
name = "node-package-exports-checker"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "node-package-exports-checker"
path = "main.rs"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
